name: guia_de_moteis_application
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  internet_connection_checker: ^3.0.1
  http: ^1.3.0
  dotenv: ^4.2.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  carousel_slider: ^5.0.0
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path: "assets/logo/guia_de_moteis_go_app_icon.jpg"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - .env

  